# Generated by Django 4.1.2 on 2022-10-15 04:16

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default='items', editable=False, max_length=150, populate_from='name')),
                ('price', models.FloatField(max_length=10)),
                ('image', models.CharField(max_length=500)),
                ('release_date', models.CharField(max_length=20)),
                ('lte_exists', models.BooleanField()),
            ],
        ),
    ]
